library common_utils_v2;

/// 三方插件 通用包
export 'package:dio/dio.dart';
export 'package:flutter_xupdate/flutter_xupdate.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:flutter_sound_lite/flutter_sound.dart';
export 'package:flutter_sound_lite/public/flutter_sound_recorder.dart';
export 'package:flutter_sound_platform_interface/flutter_sound_recorder_platform_interface.dart';
export 'package:path_provider/path_provider.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:pointycastle/asymmetric/api.dart';
export 'package:barcode_scan2/barcode_scan2.dart';
export 'package:connectivity/connectivity.dart';
export 'package:flutter_scankit/scan_kit_widget.dart';
export 'package:photo_view/photo_view.dart';
export 'package:photo_view/photo_view_gallery.dart';
export 'package:provider/provider.dart';
export 'package:flutter_easyrefresh/easy_refresh.dart';
export 'package:flutter_easyloading/flutter_easyloading.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:image_gallery_saver/image_gallery_saver.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:webview_flutter/webview_flutter.dart';
export 'package:expressions/expressions.dart';
export 'package:flutter_swiper_plus/flutter_swiper_plus.dart';
export 'package:badges/badges.dart';
export 'package:flutter_scankit/scan_kit_widget.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'package:uuid/uuid.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:fancy_bottom_navigation/fancy_bottom_navigation.dart';
export 'package:curved_navigation_bar/curved_navigation_bar.dart';
export 'package:flutter_sound_lite/flutter_sound.dart';
export 'package:path_provider/path_provider.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:image_picker/image_picker.dart';
export 'package:qr_flutter/qr_flutter.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:flutter_xupdate/flutter_xupdate.dart';
export 'package:web_socket_channel/web_socket_channel.dart';
export 'package:web_socket_channel/status.dart';
export 'package:just_the_tooltip/just_the_tooltip.dart';
export 'package:logger/logger.dart';
export 'package:flutter_native_splash/flutter_native_splash.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart';
export 'package:sqflite/sqflite.dart';
export 'package:flutter_image_compress_common/flutter_image_compress_common.dart';
export 'package:flutter_app_badger/flutter_app_badger.dart';
export 'package:quick_actions/quick_actions.dart';
export 'package:english_words/english_words.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';
export 'package:geolocator/geolocator.dart' hide ServiceStatus;
export 'package:geolocator_android/geolocator_android.dart' hide ServiceStatus;
export 'package:geolocator_apple/geolocator_apple.dart';
export 'package:chewie/chewie.dart';
export 'package:video_player/video_player.dart';
export 'package:username/username.dart';
export 'package:lpinyin/lpinyin.dart';
export 'package:bot_toast/bot_toast.dart';
export 'package:intl/intl.dart';
export 'package:workmanager/workmanager.dart';
export 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart' hide ImageSource;
export 'package:package_info_plus/package_info_plus.dart';
export 'package:wechat_assets_picker/wechat_assets_picker.dart';
export 'package:pinput/pin_put/pin_put.dart';
export 'package:lottie/lottie.dart';

/// 通用 widget
export 'src/widgets/base_dialog_widget.dart';
export 'src/widgets/base_state_widget.dart';
export 'src/widgets/common_bottom_bar.dart';
export 'src/widgets/common_bottom_selector.dart';
export 'src/widgets/refresh_widget.dart';
export 'src/widgets/swiper_widget.dart';
export 'src/widgets/marquee_widget.dart';
export 'src/widgets/common_app_bar.dart';

/// 公共页面
export 'src/pages/image_preview_page.dart';
export 'src/pages/scankit_page.dart';
export 'src/pages/web_view_page.dart';
export 'src/pages/web_view_plugin_page.dart';

/// 解决export文件冲突
export 'src/conflict/conflict.dart';

/// 模型/常量
export 'src/constants/http_code.dart';
export 'src/model/common_bottom_sheet_model.dart';
export 'src/model/base_model.dart';

/// 工具包
export 'src/utils/app_util.dart';
export 'src/utils/color_util.dart';
export 'src/utils/connectivity_util.dart';
export 'src/utils/device_info_util.dart';
export 'src/utils/encrypt_util.dart';
export 'src/utils/event_bus_util.dart';
export 'src/utils/file_compress_util.dart';
export 'src/utils/file_download_util.dart';
export 'src/utils/file_upload_util.dart';
export 'src/utils/function_proxy.dart';
export 'src/utils/http_helper_util.dart';
export 'src/utils/image_picker_util.dart';
export 'src/utils/loading_util.dart';
export 'src/utils/location_util.dart';
export 'src/utils/log_plus_util.dart';
export 'src/utils/log_util.dart';
export 'src/utils/map_navigation_util.dart';
export 'src/utils/notification_util.dart';
export 'src/utils/permission_util.dart';
export 'src/utils/qr_scanner_util.dart';
export 'src/utils/random_name_util.dart';
export 'src/utils/record_util.dart';
export 'src/utils/reg_exp_util.dart';
export 'src/utils/shared_preferences_util.dart';
export 'src/utils/sqlite_helper_util.dart';
export 'src/utils/storage_size_util.dart';
export 'src/utils/text_util.dart';
export 'src/utils/time_util.dart';
export 'src/utils/toast_util.dart';
export 'src/utils/url_encode_util.dart';
export 'src/utils/x_update_util.dart';
